services:
  redis:
    image: redis:7-alpine        
    container_name: api-caching
    restart: unless-stopped
    env_file:
      - ./apps/api/.env
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  api:
    container_name: api-server
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    env_file:
      - ./apps/api/.env
    environment:
      NODE_ENV: production     
      REDIS_HOST: redis       
    ports:
      - "${APP_PORT:-8000}:8000"
    depends_on:
      redis:
        condition: service_healthy

  web:
    container_name: web-app
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    env_file:
      - ./apps/web/.env
    environment:
      NODE_ENV: production
    ports:
      - "${WEB_PORT:-3000}:3000"

volumes:
  redis-data:
    driver: local
    