import type { Metadata } from 'next';

import '@link-sharing-app/design-system/styles.css';
import '@link-sharing-app/ui/styles.css';
import './styles.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
