services:
  redis:
    image: redis:7-alpine        
    container_name: api-caching
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: