name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

env:
  TURBO_CACHE_DIR: .turbo
  # Vars não sensíveis usadas em todos os jobs
  APP_PORT: 8000
  APP_NAME: 'Link Sharing App'
  APP_DESCRIPTION: 'A simple app for sharing links'
  APP_VERSION: '1.0.0'
  NODE_ENV: test
  REDIS_HOST: localhost
  REDIS_PORT: 6379

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # ➊ checkout obrigatório antes da action local
      - uses: ./.github/actions/common-setup # ➋ composite action
      - run: pnpm install --frozen-lockfile
      - run: pnpm turbo run lint

  build:
    name: Build Project
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      DATABASE_URL: 'file:./tmp/ci.sqlite'
      SERVICE_NAME: 'Link Sharing API'
      SERVICE_DESCRIPTION: 'A simple API for sharing links'
      SERVICE_VERSION: '0.0.1'
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
      JWT_REFRESH_EXPIRATION: '7d'
      HMAC_SECRET: ${{ secrets.HMAC_SECRET }}
      HMAC_ALGORITHM: 'sha256'
      EMAIL_FROM_ADDRESS: ${{ secrets.EMAIL_FROM_ADDRESS }}
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 465
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-setup
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter=@link-sharing-app/api exec prisma generate
      - run: pnpm turbo run build --filter=@link-sharing-app/api
      - name: Upload API dist
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: api-dist
          path: apps/api/dist

  test:
    name: Run Tests
    needs: build
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: 'file:./tmp/ci.sqlite'
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
      JWT_REFRESH_EXPIRATION: '7d'
      HMAC_SECRET: ${{ secrets.HMAC_SECRET }}
      HMAC_ALGORITHM: 'sha256'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-setup
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter=@link-sharing-app/api exec prisma generate
      - run: pnpm turbo run test --filter=@link-sharing-app/api -- --runInBand
      - name: Upload coverage
        if: always() && hashFiles('**/coverage/**') != ''
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: '**/coverage/**'
