name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

env:
  TURBO_CACHE_DIR: .turbo

jobs:
  setup: # job “pré‑requisito” → instala e cacheia
    name: Setup Dependencies
    runs-on: ubuntu-latest
    outputs:
      pnpm-store: ${{ steps.pnpm-cache.outputs.cache-hit }}

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 2 }

      - uses: pnpm/action-setup@v4
        with: { version: 10.7.1 }

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Cache pnpm store
        id: pnpm-cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-

      - run: pnpm install --frozen-lockfile

      - name: Cache turbo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: ${{ runner.os }}-turbo-

  lint:
    name: Lint Code
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with: { version: 10.7.1 }

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

      - name: Run Lint
        run: pnpm turbo run lint

  build:
    name: Build Project
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      DATABASE_URL: 'file:./tmp/ci.sqlite'
      APP_PORT: 8000
      APP_NAME: 'Link Sharing App'
      APP_DESCRIPTION: 'A simple app for sharing links'
      APP_VERSION: '1.0.0'
      NODE_ENV: test
      SERVICE_NAME: 'Link Sharing API'
      SERVICE_DESCRIPTION: 'A simple API for sharing links'
      SERVICE_VERSION: '0.0.1'
      REDIS_HOST: localhost
      REDIS_PORT: 6379

      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
      JWT_REFRESH_EXPIRATION: '7d'
      HMAC_SECRET: ${{ secrets.HMAC_SECRET }}
      HMAC_ALGORITHM: 'sha256'

      EMAIL_FROM_ADDRESS: ${{ secrets.EMAIL_FROM_ADDRESS }}
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 465
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 2 }

      - uses: pnpm/action-setup@v4
        with: { version: 10.7.1 }

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-

      - name: Cache Turborepo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: ${{ runner.os }}-turbo-

      - name: Cache Prisma engines
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/prisma
            node_modules/.prisma
          key: ${{ runner.os }}-prisma-${{ hashFiles('**/schema.prisma') }}

      - run: pnpm install --frozen-lockfile
      - name: Build afetados
        run: pnpm turbo run build

  test:
    name: Run Tests
    needs: build
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: 'file:./tmp/ci.sqlite'
      APP_PORT: 8000
      APP_NAME: 'Link Sharing App'
      APP_DESCRIPTION: 'A simple app for sharing links'
      APP_VERSION: '1.0.0'
      NODE_ENV: test
      SERVICE_NAME: 'Link Sharing API'
      SERVICE_DESCRIPTION: 'A simple API for sharing links'
      SERVICE_VERSION: '0.0.1'
      REDIS_HOST: localhost
      REDIS_PORT: 6379

      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
      JWT_REFRESH_EXPIRATION: '7d'
      HMAC_SECRET: ${{ secrets.HMAC_SECRET }}
      HMAC_ALGORITHM: 'sha256'
      EMAIL_FROM_ADDRESS: ${{ secrets.EMAIL_FROM_ADDRESS }}
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 465
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 2 }

      - uses: pnpm/action-setup@v3
        with: { version: 10.7.1 }

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - name: Run tests afetados
        run: pnpm turbo run test
